name: 04 - Using Actions
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        # 0. checkout the code from the repo
        # 1. Install dependencies of our react app
        # 2. Execute automated tests 
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Print folders
              run: ls 


   
